"""Deterministic, staged provider projection compiler."""

from __future__ import annotations

import hashlib
import json
import os
import re
import shutil
import tempfile
import time
import tomllib
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

from polymind import __version__
from polymind.capabilities import normalize_capabilities
from polymind.catalog import build_catalog
from polymind.model import AtomicCapability, Projection, SkillPackage
from polymind.validation import validate_repository

_FRONTMATTER_PATTERN = re.compile(r"\A---[ \t]*\r?\n(.*?)\r?\n---[ \t]*(?:\r?\n|\Z)", re.DOTALL)
_CLAUDE_FRONTMATTER_FIELDS = {"allowed-tools"}
_CLAUDE_TOOL_ACTIONS: dict[str, AtomicCapability] = {
    "Read": AtomicCapability.FILESYSTEM_READ,
    "Grep": AtomicCapability.FILESYSTEM_READ,
    "Glob": AtomicCapability.FILESYSTEM_READ,
    "Edit": AtomicCapability.FILESYSTEM_WRITE,
    "Write": AtomicCapability.FILESYSTEM_WRITE,
    "WebFetch": AtomicCapability.NETWORK_READ,
    "WebSearch": AtomicCapability.NETWORK_READ,
}
_MANAGED_DESTINATIONS = (
    Path(".agents/skills"),
    Path(".claude/skills"),
    Path("AGENTS.md"),
    Path("CLAUDE.md"),
    Path(".gemini/settings.json"),
    Path("opencode.local.example.json"),
    Path("catalog/skills.json"),
    Path("compatibility/providers.toml"),
    Path("projection.lock.json"),
)
_GENERATED_MARKER = """# Generated projection

This directory is generated by `polymind sync`. Do not edit it directly.
Edit canonical packages under `skills/`, then regenerate and verify.
"""


class ProjectionError(RuntimeError):
    """Base class for safe projection failures."""


class ProjectionConflictError(ProjectionError):
    """Existing unmanaged or drifted content would be overwritten."""


class ProjectionDriftError(ProjectionError):
    """Generated output differs from the canonical projection."""


@dataclass(frozen=True, slots=True)
class ClaudeOverlay:
    skill: str
    granted_actions: frozenset[AtomicCapability]
    frontmatter: dict[str, object]


@dataclass(frozen=True, slots=True)
class SyncResult:
    output_root: Path
    changes: tuple[str, ...]
    applied: bool
    checked: bool


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _json_bytes(value: object) -> bytes:
    return (json.dumps(value, indent=2, sort_keys=True, ensure_ascii=False) + "\n").encode()


def _write_bytes(path: Path, content: bytes, mode: int = 0o444) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        path.chmod(path.stat().st_mode | 0o200)
    path.write_bytes(content)
    path.chmod(mode)


def _parse_skill_frontmatter(path: Path) -> tuple[dict[str, Any], str]:
    text = path.read_text(encoding="utf-8")
    match = _FRONTMATTER_PATTERN.match(text)
    if match is None:
        raise ProjectionError(f"missing frontmatter in {path}")
    loaded: Any = yaml.safe_load(match.group(1))
    if not isinstance(loaded, dict) or not all(isinstance(key, str) for key in loaded):
        raise ProjectionError(f"frontmatter must be a string-keyed mapping in {path}")
    return dict(loaded), text[match.end() :]


def _render_skill_frontmatter(metadata: dict[str, Any], body: str) -> bytes:
    rendered = yaml.safe_dump(
        metadata,
        allow_unicode=True,
        default_flow_style=False,
        sort_keys=False,
        width=1000,
    )
    return f"---\n{rendered}---\n\n{body.lstrip()}".encode()


def _load_claude_overlay(path: Path, package: SkillPackage) -> ClaudeOverlay:
    try:
        raw: Any = tomllib.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, tomllib.TOMLDecodeError) as error:
        raise ProjectionError(f"cannot parse Claude overlay {path}: {error}") from error
    if not isinstance(raw, dict):
        raise ProjectionError(f"Claude overlay must be a TOML table: {path}")
    if raw.get("schema_version") != "1" or raw.get("provider") != "claude":
        raise ProjectionError(f"unsupported Claude overlay schema or provider: {path}")
    if raw.get("skill") != package.metadata.name:
        raise ProjectionError(f"Claude overlay skill does not match package: {path}")

    raw_actions = raw.get("granted_actions")
    if not isinstance(raw_actions, list) or not all(isinstance(item, str) for item in raw_actions):
        raise ProjectionError(f"granted_actions must be an array of strings: {path}")
    try:
        capabilities = normalize_capabilities(raw_actions)
    except ValueError as error:
        raise ProjectionError(f"invalid granted action in {path}: {error}") from error
    granted_actions = frozenset(
        action for capability in capabilities for action in capability.actions
    )
    if not granted_actions <= package.manifest.actions:
        broadened = sorted(action.value for action in granted_actions - package.manifest.actions)
        raise ProjectionError(
            f"Claude overlay broadens {package.metadata.name}: {', '.join(broadened)}"
        )

    frontmatter = raw.get("frontmatter", {})
    if not isinstance(frontmatter, dict) or not all(isinstance(key, str) for key in frontmatter):
        raise ProjectionError(f"frontmatter overlay must be a string-keyed table: {path}")
    unknown_fields = sorted(set(frontmatter) - _CLAUDE_FRONTMATTER_FIELDS)
    if unknown_fields:
        raise ProjectionError(
            f"Claude overlay contains non-allowlisted fields: {', '.join(unknown_fields)}"
        )

    allowed_tools = frontmatter.get("allowed-tools")
    if not isinstance(allowed_tools, str) or not allowed_tools.strip():
        raise ProjectionError(f"Claude allowed-tools must be a non-empty string: {path}")
    tool_actions: set[AtomicCapability] = set()
    for tool in allowed_tools.split():
        action = _CLAUDE_TOOL_ACTIONS.get(tool)
        if action is None:
            raise ProjectionError(
                f"Claude tool has no fail-closed capability mapping in {path}: {tool}"
            )
        tool_actions.add(action)
    if tool_actions != granted_actions:
        raise ProjectionError(
            f"Claude tool mapping does not equal granted_actions for {package.metadata.name}"
        )
    return ClaudeOverlay(package.metadata.name, granted_actions, dict(frontmatter))


class ProjectionCompiler:
    """Build and safely apply provider runtime trees from canonical packages."""

    stale_lock_seconds = 300

    def __init__(self, repository_root: Path, output_root: Path) -> None:
        self.repository_root = repository_root.resolve()
        unresolved_output = (
            output_root if output_root.is_absolute() else self.repository_root / output_root
        )
        self.output_root = unresolved_output.resolve()
        try:
            self.output_root.relative_to(self.repository_root)
        except ValueError as error:
            raise ProjectionError("output root must remain inside the repository") from error
        if self.output_root == self.repository_root:
            raise ProjectionError(
                "direct root projection is disabled; use a staged writable repository root"
            )
        self._replace: Callable[[Path, Path], None] = lambda source, destination: os.replace(
            source, destination
        )

    @property
    def _operation_lock(self) -> Path:
        return self.output_root.parent / f".{self.output_root.name}.polymind-sync.lock"

    def _acquire_lock(self, break_stale_lock: bool) -> None:
        self.output_root.parent.mkdir(parents=True, exist_ok=True)
        payload = _json_bytes({"pid": os.getpid(), "created_at": int(time.time())})
        try:
            descriptor = os.open(self._operation_lock, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o600)
        except FileExistsError as error:
            age = time.time() - self._operation_lock.stat().st_mtime
            if break_stale_lock and age > self.stale_lock_seconds:
                self._operation_lock.unlink()
                return self._acquire_lock(False)
            status = "stale" if age > self.stale_lock_seconds else "active"
            raise ProjectionConflictError(
                f"projection lock is {status}: {self._operation_lock} (age={age:.1f}s)"
            ) from error
        with os.fdopen(descriptor, "wb") as handle:
            handle.write(payload)

    def _release_lock(self) -> None:
        self._operation_lock.unlink(missing_ok=True)

    def _load_packages(self) -> tuple[SkillPackage, ...]:
        report = validate_repository(self.repository_root / "skills")
        errors = [item for item in report.diagnostics if item.severity.value == "error"]
        if errors:
            rendered = "; ".join(f"{item.code}: {item.path}" for item in errors)
            raise ProjectionError(f"canonical validation failed: {rendered}")
        return tuple(sorted(report.packages, key=lambda package: package.metadata.name))

    def _copy_package(self, package: SkillPackage, destination: Path) -> None:
        for source in sorted(package.root.rglob("*")):
            if source.is_symlink():
                raise ProjectionError(f"symlinks are forbidden in projected packages: {source}")
            relative = source.relative_to(package.root)
            target = destination / relative
            if source.is_dir():
                target.mkdir(parents=True, exist_ok=True)
                continue
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(source, target)
            source_mode = source.stat().st_mode & 0o777
            target.chmod(source_mode & ~0o222)

    def _apply_claude_overlay(self, package: SkillPackage, destination: Path) -> None:
        overlay_path = (
            self.repository_root
            / "adapters"
            / "claude"
            / "overlays"
            / f"{package.metadata.name}.toml"
        )
        if not overlay_path.is_file():
            return
        overlay = _load_claude_overlay(overlay_path, package)
        Projection(
            "claude", package, destination, overlay.granted_actions
        ).assert_narrower_than_source()
        skill_path = destination / "SKILL.md"
        metadata, body = _parse_skill_frontmatter(skill_path)
        metadata.update(overlay.frontmatter)
        _write_bytes(skill_path, _render_skill_frontmatter(metadata, body))

    def _merge_gemini_settings(self) -> dict[str, object]:
        settings_path = self.output_root / ".gemini" / "settings.json"
        settings: dict[str, object] = {}
        if settings_path.is_file():
            try:
                loaded: Any = json.loads(settings_path.read_text(encoding="utf-8"))
            except (OSError, UnicodeError, json.JSONDecodeError) as error:
                raise ProjectionConflictError(
                    f"cannot parse existing Gemini settings: {error}"
                ) from error
            if not isinstance(loaded, dict):
                raise ProjectionConflictError("existing Gemini settings must be a JSON object")
            settings = dict(loaded)
        context = settings.get("context", {})
        if not isinstance(context, dict):
            raise ProjectionConflictError("existing Gemini context setting must be an object")
        desired_names = ["AGENTS.md"]
        existing_names = context.get("fileName")
        if existing_names is not None and existing_names != desired_names:
            raise ProjectionConflictError(
                "existing Gemini context.fileName conflicts with Polymind-owned value"
            )
        updated_context = dict(context)
        updated_context["fileName"] = desired_names
        settings["context"] = updated_context
        return settings

    def _collect_hashes(self, root: Path) -> dict[str, str]:
        hashes: dict[str, str] = {}
        excluded = {Path("projection.lock.json"), Path(".gemini/settings.json")}
        for path in sorted(root.rglob("*")):
            if not path.is_file():
                continue
            relative = path.relative_to(root)
            if relative in excluded:
                continue
            hashes[relative.as_posix()] = _sha256(path)
        return hashes

    def _write_lock(self, stage: Path) -> None:
        lock = {
            "schema_version": "1",
            "generated_by": f"polymind-constellation/{__version__}",
            "files": self._collect_hashes(stage),
            "owned_config": {".gemini/settings.json": {"context.fileName": ["AGENTS.md"]}},
            "notice": "Digests detect drift; they do not prove provenance or authenticity.",
        }
        _write_bytes(stage / "projection.lock.json", _json_bytes(lock))

    def _build_stage(self, stage: Path) -> None:
        packages = self._load_packages()
        agent_skills = stage / ".agents" / "skills"
        claude_skills = stage / ".claude" / "skills"
        _write_bytes(agent_skills / "GENERATED.md", _GENERATED_MARKER.encode())
        _write_bytes(claude_skills / "GENERATED.md", _GENERATED_MARKER.encode())
        for package in packages:
            agent_destination = agent_skills / package.metadata.name
            claude_destination = claude_skills / package.metadata.name
            self._copy_package(package, agent_destination)
            self._copy_package(package, claude_destination)
            self._apply_claude_overlay(package, claude_destination)

        for skills_root, canonical in ((agent_skills, True), (claude_skills, False)):
            report = validate_repository(skills_root, canonical=canonical)
            errors = [item for item in report.diagnostics if item.severity.value == "error"]
            if errors:
                rendered = "; ".join(f"{item.code}: {item.path}" for item in errors)
                raise ProjectionError(f"generated projection validation failed: {rendered}")

        _write_bytes(stage / "AGENTS.md", (self.repository_root / "AGENTS.md").read_bytes())
        _write_bytes(stage / "CLAUDE.md", (self.repository_root / "CLAUDE.md").read_bytes())
        _write_bytes(
            stage / ".gemini" / "settings.json", _json_bytes(self._merge_gemini_settings())
        )
        _write_bytes(
            stage / "opencode.local.example.json",
            (self.repository_root / "examples/opencode-local/opencode.json").read_bytes(),
        )
        _write_bytes(
            stage / "catalog" / "skills.json",
            _json_bytes(build_catalog(packages, package_prefix=".agents/skills")),
        )
        _write_bytes(
            stage / "compatibility" / "providers.toml",
            (self.repository_root / "adapters" / "providers.toml").read_bytes(),
        )
        self._write_lock(stage)

    def _load_existing_lock(self) -> dict[str, object] | None:
        lock_path = self.output_root / "projection.lock.json"
        if lock_path.is_symlink():
            raise ProjectionConflictError("existing projection lock must not be a symlink")
        if not lock_path.is_file():
            return None
        try:
            loaded: Any = json.loads(lock_path.read_text(encoding="utf-8"))
        except (OSError, UnicodeError, json.JSONDecodeError) as error:
            raise ProjectionConflictError(
                f"cannot parse existing projection lock: {error}"
            ) from error
        if not isinstance(loaded, dict) or not isinstance(loaded.get("files"), dict):
            raise ProjectionConflictError("existing projection lock has an invalid schema")
        return dict(loaded)

    def _assert_managed_paths_are_not_symlinks(self) -> None:
        for relative in _MANAGED_DESTINATIONS:
            current = self.output_root
            for part in relative.parts:
                current /= part
                if current.is_symlink():
                    raise ProjectionConflictError(
                        f"symlinked generated projection path is forbidden: {relative}"
                    )
            if not current.is_dir():
                continue
            for path in current.rglob("*"):
                if path.is_symlink():
                    rendered = path.relative_to(self.output_root).as_posix()
                    raise ProjectionConflictError(
                        f"symlinked generated projection path is forbidden: {rendered}"
                    )

    def _assert_existing_clean(self) -> None:
        if not self.output_root.exists():
            return
        self._assert_managed_paths_are_not_symlinks()
        old_lock = self._load_existing_lock()
        protected_without_lock = [
            path
            for path in _MANAGED_DESTINATIONS
            if path != Path(".gemini/settings.json") and (self.output_root / path).exists()
        ]
        if old_lock is None:
            if protected_without_lock:
                rendered = ", ".join(path.as_posix() for path in protected_without_lock)
                raise ProjectionConflictError(
                    f"refusing to overwrite non-generated projection content: {rendered}"
                )
            return

        raw_files = old_lock["files"]
        assert isinstance(raw_files, dict)
        expected_paths: set[str] = set()
        for relative, expected_hash in raw_files.items():
            if not isinstance(relative, str) or not isinstance(expected_hash, str):
                raise ProjectionConflictError("existing projection lock contains invalid file data")
            expected_paths.add(relative)
            target = self.output_root / relative
            if not target.is_file() or _sha256(target) != expected_hash:
                raise ProjectionConflictError(f"generated file drift detected: {relative}")

        for tree in (Path(".agents/skills"), Path(".claude/skills")):
            tree_root = self.output_root / tree
            if not tree_root.exists():
                continue
            actual = {
                path.relative_to(self.output_root).as_posix()
                for path in tree_root.rglob("*")
                if path.is_file()
            }
            unknown = sorted(actual - expected_paths)
            if unknown:
                raise ProjectionConflictError(
                    f"unknown files in generated projection: {', '.join(unknown)}"
                )

        settings_path = self.output_root / ".gemini" / "settings.json"
        if settings_path.is_file():
            try:
                settings: Any = json.loads(settings_path.read_text(encoding="utf-8"))
            except (OSError, UnicodeError, json.JSONDecodeError) as error:
                raise ProjectionConflictError(
                    f"cannot parse existing Gemini settings: {error}"
                ) from error
            context = settings.get("context") if isinstance(settings, dict) else None
            if not isinstance(context, dict) or context.get("fileName") != ["AGENTS.md"]:
                raise ProjectionConflictError("generated Gemini context.fileName drift detected")

    def _changes(self, stage: Path) -> tuple[str, ...]:
        changes: list[str] = []
        staged_files = {
            path.relative_to(stage).as_posix(): path for path in stage.rglob("*") if path.is_file()
        }
        for relative, staged in sorted(staged_files.items()):
            current = self.output_root / relative
            if not current.is_file():
                changes.append(f"ADD {relative}")
            elif relative == ".gemini/settings.json":
                current_settings: Any = json.loads(current.read_text(encoding="utf-8"))
                current_context = (
                    current_settings.get("context") if isinstance(current_settings, dict) else None
                )
                if not isinstance(current_context, dict) or current_context.get("fileName") != [
                    "AGENTS.md"
                ]:
                    changes.append(f"MODIFY {relative}")
            elif current.read_bytes() != staged.read_bytes():
                changes.append(f"MODIFY {relative}")

        old_lock = self._load_existing_lock()
        if old_lock is not None:
            raw_files = old_lock["files"]
            assert isinstance(raw_files, dict)
            for relative in sorted(set(raw_files) - set(staged_files)):
                changes.append(f"REMOVE {relative}")
        return tuple(changes)

    def _apply_stage(self, stage: Path) -> None:
        self.output_root.mkdir(parents=True, exist_ok=True)
        with tempfile.TemporaryDirectory(
            prefix="polymind-backup-", dir=self.output_root.parent
        ) as backup_name:
            backup_root = Path(backup_name)
            applied: list[tuple[Path, Path, bool]] = []
            try:
                for relative in _MANAGED_DESTINATIONS:
                    staged = stage / relative
                    destination = self.output_root / relative
                    backup = backup_root / relative
                    destination.parent.mkdir(parents=True, exist_ok=True)
                    had_previous = destination.exists()
                    if had_previous:
                        backup.parent.mkdir(parents=True, exist_ok=True)
                        self._replace(destination, backup)
                    applied.append((destination, backup, had_previous))
                    self._replace(staged, destination)
            except BaseException:
                for destination, backup, had_previous in reversed(applied):
                    if destination.is_dir():
                        shutil.rmtree(destination)
                    elif destination.exists():
                        destination.unlink()
                    if had_previous and backup.exists():
                        destination.parent.mkdir(parents=True, exist_ok=True)
                        os.replace(backup, destination)
                raise

    def sync(
        self,
        *,
        apply: bool = False,
        check: bool = False,
        break_stale_lock: bool = False,
    ) -> SyncResult:
        if apply and check:
            raise ProjectionError("apply and check modes are mutually exclusive")
        self._acquire_lock(break_stale_lock)
        try:
            self._assert_existing_clean()
            with tempfile.TemporaryDirectory(
                prefix="polymind-stage-", dir=self.output_root.parent
            ) as stage_name:
                stage = Path(stage_name)
                self._build_stage(stage)
                changes = self._changes(stage)
                if check and changes:
                    raise ProjectionDriftError("projection drift:\n" + "\n".join(changes))
                if apply and changes:
                    self._apply_stage(stage)
                return SyncResult(self.output_root, changes, apply and bool(changes), check)
        finally:
            self._release_lock()


def check_projection(repository_root: Path, output_root: Path = Path("dist/repo")) -> SyncResult:
    return ProjectionCompiler(repository_root, output_root).sync(check=True)
